services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - ./app/air.toml:/app/air.toml
      - ./.env:/app/.env
    env_file:
      - .env
    ports:
      - "80:80"
