services:
  bot:
    build: 
      context: .
      network: host
    container_name: gobot
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./db:/app/db
      - ./app/static:/app/static
      - /etc/ssl/mycert:/app/certs
    env_file:
      - .env

