version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-go-bot
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    # Если нужен webhook и внешний доступ — раскомментируй:
    ports:
      - "8080:8080"
